name: Pytest Only

on:
  push:
    paths:
      - pyerrorschema/**  # Only run on changes to pyerrorschema
  workflow_dispatch:

permissions:
  contents: read

jobs:
  testing:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.8'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements/dev.txt

      - name: Run tests
        run: pytest

